// GENERATED by scripts/build-data.mjs — do not edit by hand.
// Source: Fantasy Premier League open dataset, 2025-26 season
// (github.com/vaastav/Fantasy-Premier-League). Ratings are derived from
// FPL prices and minutes; budgets/tiers are this game's design values.

export const REAL_CLUBS = [
 {
  "id": "MCI",
  "name": "Man City",
  "short": "Man City",
  "tier": 1,
  "transferBudget": 180000000,
  "wageBudget": 3600000,
  "expectation": 1,
  "color": "#6CABDD",
  "squad": [
   {
    "name": "Gianluigi Donnarumma",
    "position": "GK",
    "age": 26,
    "rating": 84
   },
   {
    "name": "James Trafford",
    "position": "GK",
    "age": 22,
    "rating": 69
   },
   {
    "name": "Marc Guéhi",
    "position": "DEF",
    "age": 25,
    "rating": 76
   },
   {
    "name": "Matheus Nunes",
    "position": "DEF",
    "age": 26,
    "rating": 77
   },
   {
    "name": "Rúben",
    "position": "DEF",
    "age": 28,
    "rating": 78
   },
   {
    "name": "Nico O'Reilly",
    "position": "DEF",
    "age": 20,
    "rating": 75
   },
   {
    "name": "Joško Gvardiol",
    "position": "DEF",
    "age": 23,
    "rating": 80
   },
   {
    "name": "Abdukodir Khusanov",
    "position": "DEF",
    "age": 21,
    "rating": 75
   },
   {
    "name": "Antoine Semenyo",
    "position": "MID",
    "age": 25,
    "rating": 77
   },
   {
    "name": "Bernardo",
    "position": "MID",
    "age": 30,
    "rating": 69
   },
   {
    "name": "Phil Foden",
    "position": "MID",
    "age": 25,
    "rating": 76
   },
   {
    "name": "Tijjani Reijnders",
    "position": "MID",
    "age": 27,
    "rating": 62
   },
   {
    "name": "Nico González Iglesias",
    "position": "MID",
    "age": 23,
    "rating": 67
   },
   {
    "name": "Rayan Cherki",
    "position": "MID",
    "age": 21,
    "rating": 69
   },
   {
    "name": "Erling Haaland",
    "position": "ATT",
    "age": 25,
    "rating": 92
   },
   {
    "name": "Jérémy Doku",
    "position": "MID",
    "age": 23,
    "rating": 69
   },
   {
    "name": "Rodrigo",
    "position": "MID",
    "age": 29,
    "rating": 68
   },
   {
    "name": "Rayan Aït-Nouri",
    "position": "DEF",
    "age": 24,
    "rating": 78
   },
   {
    "name": "Savinho",
    "position": "MID",
    "age": 21,
    "rating": 70
   },
   {
    "name": "Omar Marmoush",
    "position": "MID",
    "age": 26,
    "rating": 75
   },
   {
    "name": "Nathan Aké",
    "position": "DEF",
    "age": 30,
    "rating": 74
   }
  ]
 },
 {
  "id": "LIV",
  "name": "Liverpool",
  "short": "Liverpool",
  "tier": 1,
  "transferBudget": 160000000,
  "wageBudget": 3400000,
  "expectation": 2,
  "color": "#C8102E",
  "squad": [
   {
    "name": "Alisson Becker",
    "position": "GK",
    "age": 32,
    "rating": 82
   },
   {
    "name": "Giorgi Mamardashvili",
    "position": "GK",
    "age": 24,
    "rating": 62
   },
   {
    "name": "Virgil van Dijk",
    "position": "DEF",
    "age": 34,
    "rating": 83
   },
   {
    "name": "Ibrahima Konaté",
    "position": "DEF",
    "age": 26,
    "rating": 78
   },
   {
    "name": "Milos Kerkez",
    "position": "DEF",
    "age": 21,
    "rating": 79
   },
   {
    "name": "Conor Bradley",
    "position": "DEF",
    "age": 22,
    "rating": 72
   },
   {
    "name": "Andrew Robertson",
    "position": "DEF",
    "age": 31,
    "rating": 78
   },
   {
    "name": "Jeremie Frimpong",
    "position": "DEF",
    "age": 24,
    "rating": 78
   },
   {
    "name": "Dominik Szoboszlai",
    "position": "MID",
    "age": 24,
    "rating": 72
   },
   {
    "name": "Ryan Gravenberch",
    "position": "MID",
    "age": 23,
    "rating": 66
   },
   {
    "name": "Alexis Mac Allister",
    "position": "MID",
    "age": 26,
    "rating": 69
   },
   {
    "name": "Cody Gakpo",
    "position": "MID",
    "age": 26,
    "rating": 74
   },
   {
    "name": "Florian Wirtz",
    "position": "MID",
    "age": 22,
    "rating": 77
   },
   {
    "name": "Mohamed Salah",
    "position": "MID",
    "age": 33,
    "rating": 92
   },
   {
    "name": "Hugo Ekitiké",
    "position": "ATT",
    "age": 23,
    "rating": 80
   },
   {
    "name": "Alexander Isak",
    "position": "ATT",
    "age": 25,
    "rating": 81
   },
   {
    "name": "Darwin Núñez Ribeiro",
    "position": "ATT",
    "age": 26,
    "rating": 66
   },
   {
    "name": "Curtis Jones",
    "position": "MID",
    "age": 24,
    "rating": 64
   },
   {
    "name": "Joe Gomez",
    "position": "DEF",
    "age": 28,
    "rating": 71
   },
   {
    "name": "Federico Chiesa",
    "position": "MID",
    "age": 27,
    "rating": 67
   },
   {
    "name": "Endo Wataru",
    "position": "MID",
    "age": 32,
    "rating": 58
   }
  ]
 },
 {
  "id": "ARS",
  "name": "Arsenal",
  "short": "Arsenal",
  "tier": 1,
  "transferBudget": 160000000,
  "wageBudget": 3300000,
  "expectation": 3,
  "color": "#EF0107",
  "squad": [
   {
    "name": "David Raya Martín",
    "position": "GK",
    "age": 29,
    "rating": 88
   },
   {
    "name": "Arrizabalaga",
    "position": "GK",
    "age": 30,
    "rating": 60
   },
   {
    "name": "Jurriën Timber",
    "position": "DEF",
    "age": 24,
    "rating": 84
   },
   {
    "name": "Gabriel",
    "position": "DEF",
    "age": 27,
    "rating": 90
   },
   {
    "name": "William Saliba",
    "position": "DEF",
    "age": 24,
    "rating": 83
   },
   {
    "name": "Piero Hincapié",
    "position": "DEF",
    "age": 23,
    "rating": 74
   },
   {
    "name": "Riccardo Calafiori",
    "position": "DEF",
    "age": 23,
    "rating": 78
   },
   {
    "name": "Cristhian Mosquera",
    "position": "DEF",
    "age": 21,
    "rating": 75
   },
   {
    "name": "Zubimendi",
    "position": "MID",
    "age": 26,
    "rating": 64
   },
   {
    "name": "Declan Rice",
    "position": "MID",
    "age": 26,
    "rating": 74
   },
   {
    "name": "Bukayo Saka",
    "position": "MID",
    "age": 23,
    "rating": 82
   },
   {
    "name": "Leandro Trossard",
    "position": "MID",
    "age": 30,
    "rating": 71
   },
   {
    "name": "Eberechi Eze",
    "position": "MID",
    "age": 27,
    "rating": 72
   },
   {
    "name": "Martin Ødegaard",
    "position": "MID",
    "age": 26,
    "rating": 74
   },
   {
    "name": "Viktor Gyökeres",
    "position": "ATT",
    "age": 27,
    "rating": 79
   },
   {
    "name": "G.Jesus",
    "position": "ATT",
    "age": 28,
    "rating": 68
   },
   {
    "name": "Kai Havertz",
    "position": "ATT",
    "age": 26,
    "rating": 72
   },
   {
    "name": "Mikel Merino Zazón",
    "position": "MID",
    "age": 29,
    "rating": 64
   },
   {
    "name": "Noni Madueke",
    "position": "MID",
    "age": 23,
    "rating": 71
   },
   {
    "name": "Martinelli",
    "position": "MID",
    "age": 24,
    "rating": 71
   },
   {
    "name": "Benjamin White",
    "position": "DEF",
    "age": 27,
    "rating": 73
   }
  ]
 },
 {
  "id": "CHE",
  "name": "Chelsea",
  "short": "Chelsea",
  "tier": 1,
  "transferBudget": 170000000,
  "wageBudget": 3200000,
  "expectation": 4,
  "color": "#034694",
  "squad": [
   {
    "name": "Robert Lynch Sánchez",
    "position": "GK",
    "age": 27,
    "rating": 76
   },
   {
    "name": "Filip Jörgensen",
    "position": "GK",
    "age": 23,
    "rating": 66
   },
   {
    "name": "Trevoh Chalobah",
    "position": "DEF",
    "age": 26,
    "rating": 79
   },
   {
    "name": "Marc Cucurella Saseta",
    "position": "DEF",
    "age": 27,
    "rating": 82
   },
   {
    "name": "Reece James",
    "position": "DEF",
    "age": 25,
    "rating": 79
   },
   {
    "name": "Malo Gusto",
    "position": "DEF",
    "age": 22,
    "rating": 73
   },
   {
    "name": "Wesley Fofana",
    "position": "DEF",
    "age": 24,
    "rating": 67
   },
   {
    "name": "Tosin Adarabioyo",
    "position": "DEF",
    "age": 27,
    "rating": 60
   },
   {
    "name": "Enzo Fernández",
    "position": "MID",
    "age": 24,
    "rating": 71
   },
   {
    "name": "Pedro Lomba Neto",
    "position": "MID",
    "age": 25,
    "rating": 72
   },
   {
    "name": "Moisés Caicedo Corozo",
    "position": "MID",
    "age": 23,
    "rating": 67
   },
   {
    "name": "Cole Palmer",
    "position": "MID",
    "age": 23,
    "rating": 83
   },
   {
    "name": "Garnacho",
    "position": "MID",
    "age": 21,
    "rating": 69
   },
   {
    "name": "Andrey Santos",
    "position": "MID",
    "age": 21,
    "rating": 58
   },
   {
    "name": "João Pedro",
    "position": "ATT",
    "age": 23,
    "rating": 75
   },
   {
    "name": "Liam Delap",
    "position": "ATT",
    "age": 22,
    "rating": 67
   },
   {
    "name": "Marc Guiu Paz",
    "position": "ATT",
    "age": 19,
    "rating": 52
   },
   {
    "name": "Estêvão",
    "position": "MID",
    "age": 18,
    "rating": 68
   },
   {
    "name": "Josh Acheampong",
    "position": "DEF",
    "age": 19,
    "rating": 52
   },
   {
    "name": "Jorrel Hato",
    "position": "DEF",
    "age": 19,
    "rating": 68
   },
   {
    "name": "Jamie Bynoe-Gittens",
    "position": "MID",
    "age": 20,
    "rating": 66
   }
  ]
 },
 {
  "id": "MUN",
  "name": "Man Utd",
  "short": "Man Utd",
  "tier": 2,
  "transferBudget": 130000000,
  "wageBudget": 3300000,
  "expectation": 5,
  "color": "#DA291C",
  "squad": [
   {
    "name": "Senne Lammens",
    "position": "GK",
    "age": 23,
    "rating": 78
   },
   {
    "name": "Altay Bayındır",
    "position": "GK",
    "age": 27,
    "rating": 72
   },
   {
    "name": "Luke Shaw",
    "position": "DEF",
    "age": 30,
    "rating": 69
   },
   {
    "name": "Diogo Dalot Teixeira",
    "position": "DEF",
    "age": 26,
    "rating": 70
   },
   {
    "name": "Leny Yoro",
    "position": "DEF",
    "age": 19,
    "rating": 63
   },
   {
    "name": "Patrick Dorgu",
    "position": "DEF",
    "age": 20,
    "rating": 64
   },
   {
    "name": "Matthijs de Ligt",
    "position": "DEF",
    "age": 25,
    "rating": 72
   },
   {
    "name": "Harry Maguire",
    "position": "DEF",
    "age": 32,
    "rating": 67
   },
   {
    "name": "Bruno Borges Fernandes",
    "position": "MID",
    "age": 30,
    "rating": 83
   },
   {
    "name": "Bryan Mbeumo",
    "position": "MID",
    "age": 25,
    "rating": 78
   },
   {
    "name": "Casemiro",
    "position": "MID",
    "age": 33,
    "rating": 66
   },
   {
    "name": "Cunha",
    "position": "MID",
    "age": 26,
    "rating": 76
   },
   {
    "name": "Amad Diallo",
    "position": "MID",
    "age": 23,
    "rating": 69
   },
   {
    "name": "Kobbie Mainoo",
    "position": "MID",
    "age": 20,
    "rating": 59
   },
   {
    "name": "Benjamin Sesko",
    "position": "ATT",
    "age": 22,
    "rating": 73
   },
   {
    "name": "Joshua Zirkzee",
    "position": "ATT",
    "age": 24,
    "rating": 65
   },
   {
    "name": "Rasmus Højlund",
    "position": "ATT",
    "age": 22,
    "rating": 66
   },
   {
    "name": "Lisandro Martínez",
    "position": "DEF",
    "age": 27,
    "rating": 71
   },
   {
    "name": "Mason Mount",
    "position": "MID",
    "age": 26,
    "rating": 67
   },
   {
    "name": "Manuel Ugarte Ribeiro",
    "position": "MID",
    "age": 24,
    "rating": 59
   },
   {
    "name": "Ayden Heaven",
    "position": "DEF",
    "age": 18,
    "rating": 52
   }
  ]
 },
 {
  "id": "NEW",
  "name": "Newcastle",
  "short": "Newcastle",
  "tier": 2,
  "transferBudget": 110000000,
  "wageBudget": 2400000,
  "expectation": 6,
  "color": "#241F20",
  "squad": [
   {
    "name": "Nick Pope",
    "position": "GK",
    "age": 33,
    "rating": 79
   },
   {
    "name": "Aaron Ramsdale",
    "position": "GK",
    "age": 27,
    "rating": 73
   },
   {
    "name": "Malick Thiaw",
    "position": "DEF",
    "age": 23,
    "rating": 74
   },
   {
    "name": "Dan Burn",
    "position": "DEF",
    "age": 33,
    "rating": 74
   },
   {
    "name": "Lewis Hall",
    "position": "DEF",
    "age": 20,
    "rating": 77
   },
   {
    "name": "Kieran Trippier",
    "position": "DEF",
    "age": 34,
    "rating": 72
   },
   {
    "name": "Fabian Schär",
    "position": "DEF",
    "age": 33,
    "rating": 75
   },
   {
    "name": "Sven Botman",
    "position": "DEF",
    "age": 25,
    "rating": 72
   },
   {
    "name": "Sandro Tonali",
    "position": "MID",
    "age": 25,
    "rating": 64
   },
   {
    "name": "Bruno G.",
    "position": "MID",
    "age": 27,
    "rating": 72
   },
   {
    "name": "Joelinton",
    "position": "MID",
    "age": 28,
    "rating": 68
   },
   {
    "name": "Anthony Gordon",
    "position": "MID",
    "age": 24,
    "rating": 73
   },
   {
    "name": "Harvey Barnes",
    "position": "MID",
    "age": 27,
    "rating": 68
   },
   {
    "name": "Jacob Murphy",
    "position": "MID",
    "age": 30,
    "rating": 67
   },
   {
    "name": "Nick Woltemade",
    "position": "ATT",
    "age": 23,
    "rating": 71
   },
   {
    "name": "Yoane Wissa",
    "position": "ATT",
    "age": 28,
    "rating": 72
   },
   {
    "name": "William Osula",
    "position": "ATT",
    "age": 21,
    "rating": 63
   },
   {
    "name": "Lewis Miley",
    "position": "MID",
    "age": 19,
    "rating": 57
   },
   {
    "name": "Anthony Elanga",
    "position": "MID",
    "age": 23,
    "rating": 69
   },
   {
    "name": "Tino Livramento",
    "position": "DEF",
    "age": 22,
    "rating": 72
   },
   {
    "name": "Jacob Ramsey",
    "position": "MID",
    "age": 24,
    "rating": 63
   }
  ]
 },
 {
  "id": "TOT",
  "name": "Spurs",
  "short": "Spurs",
  "tier": 2,
  "transferBudget": 110000000,
  "wageBudget": 2500000,
  "expectation": 7,
  "color": "#132257",
  "squad": [
   {
    "name": "Guglielmo Vicario",
    "position": "GK",
    "age": 28,
    "rating": 74
   },
   {
    "name": "Brandon Austin",
    "position": "GK",
    "age": 26,
    "rating": 55
   },
   {
    "name": "Micky van de Ven",
    "position": "DEF",
    "age": 24,
    "rating": 68
   },
   {
    "name": "Pedro Porro Sauceda",
    "position": "DEF",
    "age": 25,
    "rating": 75
   },
   {
    "name": "Cristian Romero",
    "position": "DEF",
    "age": 27,
    "rating": 74
   },
   {
    "name": "Djed Spence",
    "position": "DEF",
    "age": 24,
    "rating": 65
   },
   {
    "name": "Destiny Udogie",
    "position": "DEF",
    "age": 22,
    "rating": 64
   },
   {
    "name": "Kevin Danso",
    "position": "DEF",
    "age": 26,
    "rating": 63
   },
   {
    "name": "J.Palhinha",
    "position": "MID",
    "age": 30,
    "rating": 66
   },
   {
    "name": "Mohammed Kudus",
    "position": "MID",
    "age": 24,
    "rating": 70
   },
   {
    "name": "Xavi Simons",
    "position": "MID",
    "age": 22,
    "rating": 70
   },
   {
    "name": "Rodrigo Bentancur",
    "position": "MID",
    "age": 28,
    "rating": 63
   },
   {
    "name": "Archie Gray",
    "position": "MID",
    "age": 19,
    "rating": 60
   },
   {
    "name": "Pape Matar Sarr",
    "position": "MID",
    "age": 22,
    "rating": 58
   },
   {
    "name": "Richarlison de Andrade",
    "position": "ATT",
    "age": 28,
    "rating": 69
   },
   {
    "name": "Randal Kolo Muani",
    "position": "ATT",
    "age": 26,
    "rating": 71
   },
   {
    "name": "Solanke",
    "position": "ATT",
    "age": 27,
    "rating": 71
   },
   {
    "name": "Wilson Odobert",
    "position": "MID",
    "age": 20,
    "rating": 63
   },
   {
    "name": "Lucas Bergvall",
    "position": "MID",
    "age": 19,
    "rating": 62
   },
   {
    "name": "Mathys Tel",
    "position": "MID",
    "age": 20,
    "rating": 67
   },
   {
    "name": "Conor Gallagher",
    "position": "MID",
    "age": 25,
    "rating": 62
   }
  ]
 },
 {
  "id": "AVL",
  "name": "Aston Villa",
  "short": "Aston Villa",
  "tier": 2,
  "transferBudget": 80000000,
  "wageBudget": 2200000,
  "expectation": 8,
  "color": "#670E36",
  "squad": [
   {
    "name": "Martinez",
    "position": "GK",
    "age": 32,
    "rating": 79
   },
   {
    "name": "Marco Bizot",
    "position": "GK",
    "age": 34,
    "rating": 64
   },
   {
    "name": "Ezri Konsa Ngoyo",
    "position": "DEF",
    "age": 27,
    "rating": 68
   },
   {
    "name": "Matty Cash",
    "position": "DEF",
    "age": 27,
    "rating": 72
   },
   {
    "name": "Lucas Digne",
    "position": "DEF",
    "age": 32,
    "rating": 68
   },
   {
    "name": "Pau Torres",
    "position": "DEF",
    "age": 28,
    "rating": 65
   },
   {
    "name": "Ian Maatsen",
    "position": "DEF",
    "age": 23,
    "rating": 64
   },
   {
    "name": "Tyrone Mings",
    "position": "DEF",
    "age": 32,
    "rating": 65
   },
   {
    "name": "Morgan Rogers",
    "position": "MID",
    "age": 23,
    "rating": 74
   },
   {
    "name": "John McGinn",
    "position": "MID",
    "age": 30,
    "rating": 64
   },
   {
    "name": "Boubacar Kamara",
    "position": "MID",
    "age": 25,
    "rating": 61
   },
   {
    "name": "Amadou Onana",
    "position": "MID",
    "age": 23,
    "rating": 60
   },
   {
    "name": "Emiliano Buendía Stati",
    "position": "MID",
    "age": 28,
    "rating": 63
   },
   {
    "name": "Youri Tielemans",
    "position": "MID",
    "age": 28,
    "rating": 67
   },
   {
    "name": "Ollie Watkins",
    "position": "ATT",
    "age": 29,
    "rating": 78
   },
   {
    "name": "Tammy Abraham",
    "position": "ATT",
    "age": 27,
    "rating": 64
   },
   {
    "name": "Zépiqueno Redmond",
    "position": "ATT",
    "age": 24,
    "rating": 56
   },
   {
    "name": "Douglas Luiz",
    "position": "MID",
    "age": 27,
    "rating": 60
   },
   {
    "name": "Lamare Bogarde",
    "position": "DEF",
    "age": 21,
    "rating": 60
   },
   {
    "name": "Jadon Sancho",
    "position": "MID",
    "age": 25,
    "rating": 65
   },
   {
    "name": "Donyell Malen",
    "position": "MID",
    "age": 26,
    "rating": 61
   }
  ]
 },
 {
  "id": "BHA",
  "name": "Brighton",
  "short": "Brighton",
  "tier": 3,
  "transferBudget": 60000000,
  "wageBudget": 1600000,
  "expectation": 9,
  "color": "#0057B8",
  "squad": [
   {
    "name": "Bart Verbruggen",
    "position": "GK",
    "age": 22,
    "rating": 71
   },
   {
    "name": "Jason Steele",
    "position": "GK",
    "age": 34,
    "rating": 62
   },
   {
    "name": "Jan Paul van Hecke",
    "position": "DEF",
    "age": 25,
    "rating": 68
   },
   {
    "name": "Lewis Dunk",
    "position": "DEF",
    "age": 33,
    "rating": 69
   },
   {
    "name": "Ferdi Kadıoğlu",
    "position": "DEF",
    "age": 25,
    "rating": 68
   },
   {
    "name": "Maxim De Cuyper",
    "position": "DEF",
    "age": 24,
    "rating": 65
   },
   {
    "name": "Joël Veltman",
    "position": "DEF",
    "age": 33,
    "rating": 65
   },
   {
    "name": "Olivier Boscagli",
    "position": "DEF",
    "age": 27,
    "rating": 63
   },
   {
    "name": "Diego Gómez Amarilla",
    "position": "MID",
    "age": 22,
    "rating": 62
   },
   {
    "name": "Yasin Ayari",
    "position": "MID",
    "age": 21,
    "rating": 61
   },
   {
    "name": "Yankuba Minteh",
    "position": "MID",
    "age": 21,
    "rating": 66
   },
   {
    "name": "Georginio Rutter",
    "position": "MID",
    "age": 23,
    "rating": 66
   },
   {
    "name": "Mitoma Kaoru",
    "position": "MID",
    "age": 28,
    "rating": 68
   },
   {
    "name": "Mats Wieffer",
    "position": "MID",
    "age": 25,
    "rating": 61
   },
   {
    "name": "Danny Welbeck",
    "position": "ATT",
    "age": 34,
    "rating": 69
   },
   {
    "name": "Charalampos Kostoulas",
    "position": "ATT",
    "age": 18,
    "rating": 60
   },
   {
    "name": "Stefanos Tzimas",
    "position": "ATT",
    "age": 19,
    "rating": 60
   },
   {
    "name": "Carlos Baleba",
    "position": "MID",
    "age": 21,
    "rating": 58
   },
   {
    "name": "Jack Hinshelwood",
    "position": "MID",
    "age": 20,
    "rating": 62
   },
   {
    "name": "Pascal Groß",
    "position": "MID",
    "age": 34,
    "rating": 65
   },
   {
    "name": "Brajan Gruda",
    "position": "MID",
    "age": 21,
    "rating": 63
   }
  ]
 },
 {
  "id": "CRY",
  "name": "Crystal Palace",
  "short": "CRY",
  "tier": 3,
  "transferBudget": 50000000,
  "wageBudget": 1500000,
  "expectation": 10,
  "color": "#1B458F",
  "squad": [
   {
    "name": "Dean Henderson",
    "position": "GK",
    "age": 28,
    "rating": 78
   },
   {
    "name": "Walter Benítez",
    "position": "GK",
    "age": 32,
    "rating": 58
   },
   {
    "name": "Tyrick Mitchell",
    "position": "DEF",
    "age": 25,
    "rating": 74
   },
   {
    "name": "Maxence Lacroix",
    "position": "DEF",
    "age": 25,
    "rating": 75
   },
   {
    "name": "Chris Richards",
    "position": "DEF",
    "age": 25,
    "rating": 68
   },
   {
    "name": "Daniel Muñoz Mejía",
    "position": "DEF",
    "age": 29,
    "rating": 81
   },
   {
    "name": "Jaydee Canvot",
    "position": "DEF",
    "age": 19,
    "rating": 67
   },
   {
    "name": "Nathaniel Clyne",
    "position": "DEF",
    "age": 34,
    "rating": 56
   },
   {
    "name": "Adam Wharton",
    "position": "MID",
    "age": 21,
    "rating": 63
   },
   {
    "name": "Yéremy Pino Santos",
    "position": "MID",
    "age": 22,
    "rating": 67
   },
   {
    "name": "Ismaïla Sarr",
    "position": "MID",
    "age": 27,
    "rating": 69
   },
   {
    "name": "Daichi Kamada",
    "position": "MID",
    "age": 28,
    "rating": 62
   },
   {
    "name": "Will Hughes",
    "position": "MID",
    "age": 30,
    "rating": 60
   },
   {
    "name": "Jefferson Lerma Solís",
    "position": "MID",
    "age": 30,
    "rating": 61
   },
   {
    "name": "Jean-Philippe Mateta",
    "position": "ATT",
    "age": 28,
    "rating": 74
   },
   {
    "name": "Jørgen Strand Larsen",
    "position": "ATT",
    "age": 25,
    "rating": 69
   },
   {
    "name": "Eddie Nketiah",
    "position": "ATT",
    "age": 26,
    "rating": 63
   },
   {
    "name": "Brennan Johnson",
    "position": "MID",
    "age": 24,
    "rating": 69
   },
   {
    "name": "Evann Guessand",
    "position": "MID",
    "age": 24,
    "rating": 67
   },
   {
    "name": "Justin Devenny",
    "position": "MID",
    "age": 21,
    "rating": 54
   },
   {
    "name": "Chadi Riad Dnanou",
    "position": "DEF",
    "age": 22,
    "rating": 60
   }
  ]
 },
 {
  "id": "WHU",
  "name": "West Ham",
  "short": "West Ham",
  "tier": 3,
  "transferBudget": 55000000,
  "wageBudget": 1800000,
  "expectation": 11,
  "color": "#7A263A",
  "squad": [
   {
    "name": "Alphonse Areola",
    "position": "GK",
    "age": 32,
    "rating": 68
   },
   {
    "name": "Mads Hermansen",
    "position": "GK",
    "age": 25,
    "rating": 65
   },
   {
    "name": "El Hadji Malick Diouf",
    "position": "DEF",
    "age": 20,
    "rating": 62
   },
   {
    "name": "Aaron Wan-Bissaka",
    "position": "DEF",
    "age": 27,
    "rating": 64
   },
   {
    "name": "Mavropanos",
    "position": "DEF",
    "age": 27,
    "rating": 68
   },
   {
    "name": "Jean-Clair Todibo",
    "position": "DEF",
    "age": 25,
    "rating": 66
   },
   {
    "name": "Maximilian Kilman",
    "position": "DEF",
    "age": 28,
    "rating": 64
   },
   {
    "name": "Kyle Walker-Peters",
    "position": "DEF",
    "age": 28,
    "rating": 64
   },
   {
    "name": "M.Fernandes",
    "position": "MID",
    "age": 21,
    "rating": 66
   },
   {
    "name": "Crysencio Summerville",
    "position": "MID",
    "age": 23,
    "rating": 67
   },
   {
    "name": "L.Paquetá",
    "position": "MID",
    "age": 27,
    "rating": 68
   },
   {
    "name": "Tomáš Souček",
    "position": "MID",
    "age": 30,
    "rating": 66
   },
   {
    "name": "Freddie Potts",
    "position": "MID",
    "age": 21,
    "rating": 57
   },
   {
    "name": "Soungoutou Magassa",
    "position": "MID",
    "age": 21,
    "rating": 62
   },
   {
    "name": "Jarrod Bowen",
    "position": "ATT",
    "age": 28,
    "rating": 74
   },
   {
    "name": "Callum Wilson",
    "position": "ATT",
    "age": 33,
    "rating": 66
   },
   {
    "name": "Valentín Castellanos",
    "position": "ATT",
    "age": 26,
    "rating": 64
   },
   {
    "name": "Ollie Scarles",
    "position": "DEF",
    "age": 19,
    "rating": 64
   },
   {
    "name": "Axel Disasi",
    "position": "DEF",
    "age": 27,
    "rating": 67
   },
   {
    "name": "Niclas Füllkrug",
    "position": "ATT",
    "age": 32,
    "rating": 64
   },
   {
    "name": "Adama Traoré Diarra",
    "position": "MID",
    "age": 29,
    "rating": 61
   }
  ]
 },
 {
  "id": "BRE",
  "name": "Brentford",
  "short": "Brentford",
  "tier": 3,
  "transferBudget": 45000000,
  "wageBudget": 1300000,
  "expectation": 12,
  "color": "#E30613",
  "squad": [
   {
    "name": "Caoimhín Kelleher",
    "position": "GK",
    "age": 26,
    "rating": 74
   },
   {
    "name": "Valdimarsson",
    "position": "GK",
    "age": 23,
    "rating": 55
   },
   {
    "name": "Michael Kayode",
    "position": "DEF",
    "age": 21,
    "rating": 69
   },
   {
    "name": "Nathan Collins",
    "position": "DEF",
    "age": 24,
    "rating": 73
   },
   {
    "name": "Sepp van den Berg",
    "position": "DEF",
    "age": 23,
    "rating": 69
   },
   {
    "name": "Kristoffer Ajer",
    "position": "DEF",
    "age": 27,
    "rating": 68
   },
   {
    "name": "Rico Henry",
    "position": "DEF",
    "age": 28,
    "rating": 65
   },
   {
    "name": "Keane Lewis-Potter",
    "position": "DEF",
    "age": 24,
    "rating": 71
   },
   {
    "name": "Kevin Schade",
    "position": "MID",
    "age": 23,
    "rating": 72
   },
   {
    "name": "Yehor Yarmoliuk",
    "position": "MID",
    "age": 21,
    "rating": 63
   },
   {
    "name": "Jordan Henderson",
    "position": "MID",
    "age": 35,
    "rating": 63
   },
   {
    "name": "Dango Ouattara",
    "position": "MID",
    "age": 23,
    "rating": 68
   },
   {
    "name": "Mikkel Damsgaard",
    "position": "MID",
    "age": 25,
    "rating": 65
   },
   {
    "name": "Mathias Jensen",
    "position": "MID",
    "age": 29,
    "rating": 61
   },
   {
    "name": "Thiago",
    "position": "ATT",
    "age": 24,
    "rating": 73
   },
   {
    "name": "Kaye Furo",
    "position": "ATT",
    "age": 18,
    "rating": 56
   },
   {
    "name": "Iwan Morgan",
    "position": "ATT",
    "age": 24,
    "rating": 55
   },
   {
    "name": "Vitaly Janelt",
    "position": "MID",
    "age": 27,
    "rating": 61
   },
   {
    "name": "Aaron Hickey",
    "position": "DEF",
    "age": 23,
    "rating": 60
   },
   {
    "name": "Ethan Pinnock",
    "position": "DEF",
    "age": 32,
    "rating": 63
   },
   {
    "name": "Carvalho",
    "position": "MID",
    "age": 22,
    "rating": 57
   }
  ]
 },
 {
  "id": "FUL",
  "name": "Fulham",
  "short": "Fulham",
  "tier": 3,
  "transferBudget": 45000000,
  "wageBudget": 1400000,
  "expectation": 13,
  "color": "#1D1D1B",
  "squad": [
   {
    "name": "Bernd Leno",
    "position": "GK",
    "age": 33,
    "rating": 76
   },
   {
    "name": "Steven Benda",
    "position": "GK",
    "age": 26,
    "rating": 58
   },
   {
    "name": "Joachim Andersen",
    "position": "DEF",
    "age": 29,
    "rating": 69
   },
   {
    "name": "Calvin Bassey",
    "position": "DEF",
    "age": 25,
    "rating": 68
   },
   {
    "name": "Kenny Tete",
    "position": "DEF",
    "age": 29,
    "rating": 69
   },
   {
    "name": "Timothy Castagne",
    "position": "DEF",
    "age": 29,
    "rating": 65
   },
   {
    "name": "Jorge Cuenca Barreno",
    "position": "DEF",
    "age": 25,
    "rating": 65
   },
   {
    "name": "Antonee Robinson",
    "position": "DEF",
    "age": 27,
    "rating": 72
   },
   {
    "name": "Sander Berge",
    "position": "MID",
    "age": 27,
    "rating": 62
   },
   {
    "name": "Harry Wilson",
    "position": "MID",
    "age": 28,
    "rating": 68
   },
   {
    "name": "Alex Iwobi",
    "position": "MID",
    "age": 29,
    "rating": 70
   },
   {
    "name": "Ryan Sessegnon",
    "position": "MID",
    "age": 25,
    "rating": 65
   },
   {
    "name": "Emile Smith Rowe",
    "position": "MID",
    "age": 25,
    "rating": 65
   },
   {
    "name": "Saša Lukić",
    "position": "MID",
    "age": 28,
    "rating": 61
   },
   {
    "name": "Raúl Jiménez Rodríguez",
    "position": "ATT",
    "age": 34,
    "rating": 69
   },
   {
    "name": "Rodrigo Muniz Carvalho",
    "position": "ATT",
    "age": 24,
    "rating": 63
   },
   {
    "name": "Jonah Kusi-Asare",
    "position": "ATT",
    "age": 18,
    "rating": 56
   },
   {
    "name": "Josh King",
    "position": "MID",
    "age": 18,
    "rating": 57
   },
   {
    "name": "Kevin",
    "position": "MID",
    "age": 22,
    "rating": 66
   },
   {
    "name": "Samuel Chukwueze",
    "position": "MID",
    "age": 26,
    "rating": 62
   },
   {
    "name": "Oscar Bobb",
    "position": "MID",
    "age": 22,
    "rating": 61
   }
  ]
 },
 {
  "id": "EVE",
  "name": "Everton",
  "short": "Everton",
  "tier": 3,
  "transferBudget": 45000000,
  "wageBudget": 1500000,
  "expectation": 14,
  "color": "#003399",
  "squad": [
   {
    "name": "Jordan Pickford",
    "position": "GK",
    "age": 31,
    "rating": 84
   },
   {
    "name": "Mark Travers",
    "position": "GK",
    "age": 26,
    "rating": 64
   },
   {
    "name": "James Tarkowski",
    "position": "DEF",
    "age": 32,
    "rating": 80
   },
   {
    "name": "Jake O'Brien",
    "position": "DEF",
    "age": 24,
    "rating": 73
   },
   {
    "name": "Vitalii Mykolenko",
    "position": "DEF",
    "age": 26,
    "rating": 73
   },
   {
    "name": "Michael Keane",
    "position": "DEF",
    "age": 32,
    "rating": 70
   },
   {
    "name": "Jarrad Branthwaite",
    "position": "DEF",
    "age": 23,
    "rating": 75
   },
   {
    "name": "Nathan Patterson",
    "position": "DEF",
    "age": 23,
    "rating": 66
   },
   {
    "name": "James Garner",
    "position": "MID",
    "age": 24,
    "rating": 64
   },
   {
    "name": "Iliman Ndiaye",
    "position": "MID",
    "age": 25,
    "rating": 69
   },
   {
    "name": "Kiernan Dewsbury-Hall",
    "position": "MID",
    "age": 26,
    "rating": 63
   },
   {
    "name": "Idrissa Gana Gueye",
    "position": "MID",
    "age": 35,
    "rating": 65
   },
   {
    "name": "Jack Grealish",
    "position": "MID",
    "age": 29,
    "rating": 69
   },
   {
    "name": "Tim Iroegbunam",
    "position": "MID",
    "age": 22,
    "rating": 60
   },
   {
    "name": "Thierno Barry",
    "position": "ATT",
    "age": 22,
    "rating": 67
   },
   {
    "name": "Beto",
    "position": "ATT",
    "age": 27,
    "rating": 62
   },
   {
    "name": "Y.Chermiti",
    "position": "ATT",
    "age": 21,
    "rating": 59
   },
   {
    "name": "Dwight McNeil",
    "position": "MID",
    "age": 25,
    "rating": 64
   },
   {
    "name": "Carlos Alcaraz Durán",
    "position": "MID",
    "age": 22,
    "rating": 62
   },
   {
    "name": "Harrison Armstrong",
    "position": "MID",
    "age": 18,
    "rating": 57
   },
   {
    "name": "Merlin Röhl",
    "position": "MID",
    "age": 23,
    "rating": 61
   }
  ]
 },
 {
  "id": "NFO",
  "name": "Nott'm Forest",
  "short": "NFO",
  "tier": 3,
  "transferBudget": 45000000,
  "wageBudget": 1400000,
  "expectation": 15,
  "color": "#DD0000",
  "squad": [
   {
    "name": "Matz Sels",
    "position": "GK",
    "age": 33,
    "rating": 73
   },
   {
    "name": "John",
    "position": "GK",
    "age": 29,
    "rating": 60
   },
   {
    "name": "Nikola Milenković",
    "position": "DEF",
    "age": 27,
    "rating": 75
   },
   {
    "name": "Neco Williams",
    "position": "DEF",
    "age": 24,
    "rating": 71
   },
   {
    "name": "Murillo",
    "position": "DEF",
    "age": 23,
    "rating": 76
   },
   {
    "name": "Ola Aina",
    "position": "DEF",
    "age": 28,
    "rating": 70
   },
   {
    "name": "Nicolò Savona",
    "position": "DEF",
    "age": 22,
    "rating": 68
   },
   {
    "name": "Morato",
    "position": "DEF",
    "age": 24,
    "rating": 65
   },
   {
    "name": "Elliot Anderson",
    "position": "MID",
    "age": 22,
    "rating": 66
   },
   {
    "name": "Morgan Gibbs-White",
    "position": "MID",
    "age": 25,
    "rating": 74
   },
   {
    "name": "Callum Hudson-Odoi",
    "position": "MID",
    "age": 24,
    "rating": 67
   },
   {
    "name": "Ibrahim Sangaré",
    "position": "MID",
    "age": 27,
    "rating": 62
   },
   {
    "name": "Omari Hutchinson",
    "position": "MID",
    "age": 21,
    "rating": 64
   },
   {
    "name": "Dan Ndoye",
    "position": "MID",
    "age": 24,
    "rating": 65
   },
   {
    "name": "Igor Jesus",
    "position": "ATT",
    "age": 24,
    "rating": 67
   },
   {
    "name": "Chris Wood",
    "position": "ATT",
    "age": 33,
    "rating": 71
   },
   {
    "name": "Taiwo Awoniyi",
    "position": "ATT",
    "age": 27,
    "rating": 62
   },
   {
    "name": "Nicolás Domínguez",
    "position": "MID",
    "age": 27,
    "rating": 62
   },
   {
    "name": "Ryan Yates",
    "position": "MID",
    "age": 27,
    "rating": 59
   },
   {
    "name": "Oleksandr Zinchenko",
    "position": "DEF",
    "age": 28,
    "rating": 71
   },
   {
    "name": "Dilane Bakwa",
    "position": "MID",
    "age": 22,
    "rating": 66
   }
  ]
 },
 {
  "id": "BOU",
  "name": "Bournemouth",
  "short": "Bournemouth",
  "tier": 4,
  "transferBudget": 35000000,
  "wageBudget": 1200000,
  "expectation": 16,
  "color": "#B50E12",
  "squad": [
   {
    "name": "Đorđe Petrović",
    "position": "GK",
    "age": 25,
    "rating": 71
   },
   {
    "name": "Norberto Murara Neto",
    "position": "GK",
    "age": 36,
    "rating": 67
   },
   {
    "name": "Adrien Truffert",
    "position": "DEF",
    "age": 23,
    "rating": 70
   },
   {
    "name": "Marcos Senesi Barón",
    "position": "DEF",
    "age": 28,
    "rating": 74
   },
   {
    "name": "Álex Jiménez Sánchez",
    "position": "DEF",
    "age": 20,
    "rating": 69
   },
   {
    "name": "James Hill",
    "position": "DEF",
    "age": 23,
    "rating": 64
   },
   {
    "name": "Bafodé Diakité",
    "position": "DEF",
    "age": 24,
    "rating": 64
   },
   {
    "name": "Adam Smith",
    "position": "DEF",
    "age": 34,
    "rating": 66
   },
   {
    "name": "Alex Scott",
    "position": "MID",
    "age": 21,
    "rating": 63
   },
   {
    "name": "Marcus Tavernier",
    "position": "MID",
    "age": 26,
    "rating": 64
   },
   {
    "name": "Tyler Adams",
    "position": "MID",
    "age": 26,
    "rating": 61
   },
   {
    "name": "David Brooks",
    "position": "MID",
    "age": 28,
    "rating": 62
   },
   {
    "name": "Amine Adli",
    "position": "MID",
    "age": 25,
    "rating": 64
   },
   {
    "name": "Justin Kluivert",
    "position": "MID",
    "age": 26,
    "rating": 71
   },
   {
    "name": "Evanilson",
    "position": "ATT",
    "age": 25,
    "rating": 72
   },
   {
    "name": "Junior Kroupi",
    "position": "ATT",
    "age": 19,
    "rating": 60
   },
   {
    "name": "Enes Ünal",
    "position": "ATT",
    "age": 28,
    "rating": 61
   },
   {
    "name": "Lewis Cook",
    "position": "MID",
    "age": 28,
    "rating": 61
   },
   {
    "name": "Ryan Christie",
    "position": "MID",
    "age": 30,
    "rating": 60
   },
   {
    "name": "Rayan",
    "position": "MID",
    "age": 18,
    "rating": 64
   },
   {
    "name": "Veljko Milosavljevic",
    "position": "DEF",
    "age": 18,
    "rating": 66
   }
  ]
 },
 {
  "id": "WOL",
  "name": "Wolves",
  "short": "Wolves",
  "tier": 4,
  "transferBudget": 35000000,
  "wageBudget": 1200000,
  "expectation": 17,
  "color": "#FDB913",
  "squad": [
   {
    "name": "José Malheiro de Sá",
    "position": "GK",
    "age": 32,
    "rating": 66
   },
   {
    "name": "Sam Johnstone",
    "position": "GK",
    "age": 32,
    "rating": 69
   },
   {
    "name": "Ladislav Krejcí",
    "position": "DEF",
    "age": 26,
    "rating": 69
   },
   {
    "name": "Hugo Bueno López",
    "position": "DEF",
    "age": 22,
    "rating": 66
   },
   {
    "name": "Santiago Ignacio Bueno",
    "position": "DEF",
    "age": 26,
    "rating": 68
   },
   {
    "name": "Mosquera",
    "position": "DEF",
    "age": 24,
    "rating": 66
   },
   {
    "name": "Jackson Tchatchoua",
    "position": "DEF",
    "age": 23,
    "rating": 68
   },
   {
    "name": "Emmanuel Agbadou",
    "position": "DEF",
    "age": 28,
    "rating": 64
   },
   {
    "name": "J.Gomes",
    "position": "MID",
    "age": 24,
    "rating": 64
   },
   {
    "name": "André",
    "position": "MID",
    "age": 24,
    "rating": 64
   },
   {
    "name": "Hwang Hee-chan",
    "position": "MID",
    "age": 29,
    "rating": 65
   },
   {
    "name": "Jhon Arias",
    "position": "MID",
    "age": 27,
    "rating": 61
   },
   {
    "name": "Jean-Ricner Bellegarde",
    "position": "MID",
    "age": 27,
    "rating": 62
   },
   {
    "name": "Marshall Munetsi",
    "position": "MID",
    "age": 29,
    "rating": 63
   },
   {
    "name": "Mateus Mané",
    "position": "ATT",
    "age": 17,
    "rating": 59
   },
   {
    "name": "Tolu Arokodare",
    "position": "ATT",
    "age": 24,
    "rating": 64
   },
   {
    "name": "Adam Armstrong",
    "position": "ATT",
    "age": 28,
    "rating": 63
   },
   {
    "name": "Toti Gomes",
    "position": "DEF",
    "age": 26,
    "rating": 64
   },
   {
    "name": "David Møller Wolfe",
    "position": "DEF",
    "age": 23,
    "rating": 64
   },
   {
    "name": "Matt Doherty",
    "position": "DEF",
    "age": 33,
    "rating": 66
   },
   {
    "name": "Rodrigo Martins Gomes",
    "position": "DEF",
    "age": 22,
    "rating": 66
   }
  ]
 },
 {
  "id": "LEE",
  "name": "Leeds",
  "short": "Leeds",
  "tier": 4,
  "transferBudget": 30000000,
  "wageBudget": 1100000,
  "expectation": 18,
  "color": "#1D428A",
  "squad": [
   {
    "name": "Lucas Estella Perri",
    "position": "GK",
    "age": 27,
    "rating": 70
   },
   {
    "name": "Karl Darlow",
    "position": "GK",
    "age": 34,
    "rating": 58
   },
   {
    "name": "Joe Rodon",
    "position": "DEF",
    "age": 27,
    "rating": 60
   },
   {
    "name": "Gabriel Gudmundsson",
    "position": "DEF",
    "age": 26,
    "rating": 58
   },
   {
    "name": "Jayden Bogle",
    "position": "DEF",
    "age": 25,
    "rating": 68
   },
   {
    "name": "Pascal Struijk",
    "position": "DEF",
    "age": 25,
    "rating": 66
   },
   {
    "name": "Jaka Bijol",
    "position": "DEF",
    "age": 26,
    "rating": 59
   },
   {
    "name": "James Justin",
    "position": "DEF",
    "age": 27,
    "rating": 59
   },
   {
    "name": "Ethan Ampadu",
    "position": "MID",
    "age": 24,
    "rating": 62
   },
   {
    "name": "Anton Stach",
    "position": "MID",
    "age": 26,
    "rating": 61
   },
   {
    "name": "Brenden Aaronson",
    "position": "MID",
    "age": 24,
    "rating": 65
   },
   {
    "name": "Noah Okafor",
    "position": "MID",
    "age": 25,
    "rating": 65
   },
   {
    "name": "Ilia Gruev",
    "position": "MID",
    "age": 25,
    "rating": 60
   },
   {
    "name": "Sean Longstaff",
    "position": "MID",
    "age": 27,
    "rating": 60
   },
   {
    "name": "Dominic Calvert-Lewin",
    "position": "ATT",
    "age": 28,
    "rating": 67
   },
   {
    "name": "Lukas Nmecha",
    "position": "ATT",
    "age": 26,
    "rating": 61
   },
   {
    "name": "Joël Piroe",
    "position": "ATT",
    "age": 25,
    "rating": 61
   },
   {
    "name": "Tanaka Ao",
    "position": "MID",
    "age": 26,
    "rating": 59
   },
   {
    "name": "Daniel James",
    "position": "MID",
    "age": 27,
    "rating": 62
   },
   {
    "name": "Wilfried Gnonto",
    "position": "MID",
    "age": 21,
    "rating": 62
   },
   {
    "name": "Sebastiaan Bornauw",
    "position": "DEF",
    "age": 26,
    "rating": 56
   }
  ]
 },
 {
  "id": "SUN",
  "name": "Sunderland",
  "short": "Sunderland",
  "tier": 4,
  "transferBudget": 25000000,
  "wageBudget": 900000,
  "expectation": 19,
  "color": "#EB172B",
  "squad": [
   {
    "name": "Robin Roefs",
    "position": "GK",
    "age": 22,
    "rating": 75
   },
   {
    "name": "Melker Ellborg",
    "position": "GK",
    "age": 22,
    "rating": 58
   },
   {
    "name": "Trai Hume",
    "position": "DEF",
    "age": 23,
    "rating": 69
   },
   {
    "name": "Omar Alderete",
    "position": "DEF",
    "age": 28,
    "rating": 64
   },
   {
    "name": "Nordi Mukiele",
    "position": "DEF",
    "age": 27,
    "rating": 69
   },
   {
    "name": "Daniel Ballard",
    "position": "DEF",
    "age": 25,
    "rating": 70
   },
   {
    "name": "Reinildo Mandava",
    "position": "DEF",
    "age": 31,
    "rating": 57
   },
   {
    "name": "Lutsharel Geertruida",
    "position": "DEF",
    "age": 25,
    "rating": 68
   },
   {
    "name": "Enzo Le Fée",
    "position": "MID",
    "age": 25,
    "rating": 63
   },
   {
    "name": "Noah Sadiki",
    "position": "MID",
    "age": 20,
    "rating": 62
   },
   {
    "name": "Granit Xhaka",
    "position": "MID",
    "age": 32,
    "rating": 63
   },
   {
    "name": "Chemsdine Talbi",
    "position": "MID",
    "age": 20,
    "rating": 61
   },
   {
    "name": "Habib Diarra",
    "position": "MID",
    "age": 21,
    "rating": 63
   },
   {
    "name": "Simon Adingra",
    "position": "MID",
    "age": 23,
    "rating": 60
   },
   {
    "name": "Brian Brobbey",
    "position": "ATT",
    "age": 23,
    "rating": 64
   },
   {
    "name": "Wilson Isidor",
    "position": "ATT",
    "age": 24,
    "rating": 63
   },
   {
    "name": "Eliezer Mayenda Dossou",
    "position": "ATT",
    "age": 20,
    "rating": 62
   },
   {
    "name": "Bertrand Traoré",
    "position": "MID",
    "age": 29,
    "rating": 64
   },
   {
    "name": "Romaine Mundle",
    "position": "MID",
    "age": 22,
    "rating": 60
   },
   {
    "name": "Chris Rigg",
    "position": "MID",
    "age": 18,
    "rating": 59
   },
   {
    "name": "Dennis Cirkin",
    "position": "DEF",
    "age": 23,
    "rating": 60
   }
  ]
 },
 {
  "id": "BUR",
  "name": "Burnley",
  "short": "Burnley",
  "tier": 4,
  "transferBudget": 20000000,
  "wageBudget": 800000,
  "expectation": 20,
  "color": "#6C1D45",
  "squad": [
   {
    "name": "Martin Dúbravka",
    "position": "GK",
    "age": 36,
    "rating": 62
   },
   {
    "name": "Max Weiß",
    "position": "GK",
    "age": 21,
    "rating": 64
   },
   {
    "name": "Kyle Walker",
    "position": "DEF",
    "age": 35,
    "rating": 68
   },
   {
    "name": "Maxime Estève",
    "position": "DEF",
    "age": 23,
    "rating": 60
   },
   {
    "name": "Quilindschy Hartman",
    "position": "DEF",
    "age": 23,
    "rating": 61
   },
   {
    "name": "Hjalmar Ekdal",
    "position": "DEF",
    "age": 26,
    "rating": 57
   },
   {
    "name": "Lucas Pires Silva",
    "position": "DEF",
    "age": 24,
    "rating": 57
   },
   {
    "name": "Bashir Humphreys",
    "position": "DEF",
    "age": 22,
    "rating": 59
   },
   {
    "name": "Jaidon Anthony",
    "position": "MID",
    "age": 25,
    "rating": 63
   },
   {
    "name": "Lesley Ugochukwu",
    "position": "MID",
    "age": 21,
    "rating": 63
   },
   {
    "name": "Florentino",
    "position": "MID",
    "age": 25,
    "rating": 63
   },
   {
    "name": "Josh Cullen",
    "position": "MID",
    "age": 29,
    "rating": 62
   },
   {
    "name": "Josh Laurent",
    "position": "MID",
    "age": 30,
    "rating": 60
   },
   {
    "name": "Jacob Bruun Larsen",
    "position": "MID",
    "age": 26,
    "rating": 63
   },
   {
    "name": "Lyle Foster",
    "position": "ATT",
    "age": 24,
    "rating": 62
   },
   {
    "name": "Zian Flemming",
    "position": "ATT",
    "age": 27,
    "rating": 64
   },
   {
    "name": "Armando Broja",
    "position": "ATT",
    "age": 23,
    "rating": 63
   },
   {
    "name": "Axel Tuanzebe",
    "position": "DEF",
    "age": 27,
    "rating": 59
   },
   {
    "name": "Hannibal Mejbri",
    "position": "MID",
    "age": 22,
    "rating": 60
   },
   {
    "name": "Marcus Edwards",
    "position": "MID",
    "age": 26,
    "rating": 60
   },
   {
    "name": "Loum Tchaouna",
    "position": "MID",
    "age": 21,
    "rating": 61
   }
  ]
 }
];

export const DERBIES = [["MCI","MUN"],["LIV","EVE"],["ARS","TOT"],["CHE","FUL"],["WHU","TOT"],["CRY","BHA"],["SUN","NEW"],["LEE","MUN"]];

export const STARTER_CLUB_IDS = ["CHE","WHU","BUR"];
